language: node_js
os: osx
notifications:
  email: false
install:
  - npm install coveralls istanbul
script:
  - npm run test
after_script:
  - ./node_modules/.bin/istanbul cover --include-all-sources test.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
