os:
  - osx
language: node_js
sudo: false
node_js:
  - "node"
  - "--lts"
notifications:
  email: false
install:
  - npm ci
script:
  - npm test
after_script:
  - ./node_modules/.bin/istanbul cover test.js
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
