os: osx
notifications:
  email: false
before_install:
  - brew update
  - brew install node
install:
  - npm install coveralls istanbul
before_script:
    - uname -a
script:
  - npm run test
after_script:
  - ./node_modules/.bin/istanbul cover --include-all-sources test.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
