os:
  - osx
language: node_js
sudo: false
node_js:
  - "node"
  - "--lts"
notifications:
  email: false
install:
  - npm ci
script:
  - npm run lint
  - npm run test
after_script:
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls
