os:
  - osx
language: node_js
sudo: false
node_js:
  - "node"
  - "--lts"
  - "0.12"
notifications:
  email: false
install:
  - npm install
  - npm install -g
  - npm install coveralls istanbul
script:
  - npm test
  - get-osx-version
after_script:
  - ./node_modules/.bin/istanbul cover test.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
