os:
  - osx
language: node_js
sudo: false
node_js:
  - "node"
  - "--lts"
  - "0.12"
notifications:
  email: false
install:
  - npm ci
script:
  - npm test
after_script:
  - ./node_modules/.bin/istanbul cover test.js
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
matrix:
  include:
    - node_js: "0.12"
      before_install: "npm install -g npm@latest"
