os: osx
notifications:
  email: false
install:
  - npm install coveralls istanbul
script:
  - npm test
after_script:
  - ./node_modules/.bin/istanbul cover test.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
sudo: false
